### ISSUE TITLE
OOV Handling

### ISSUE THREAD

**Issue by sorami** [WorksApplications/sudachi.rs#1]
Currently, no OOV handling at all. 

Thus the tokenizer will sometimes panic when there is no word in the dictionary for the input.

e.g.,

```
$ echo Sudachi | sudachi
thread 'main' panicked at 'EOS isn't connected to BOS', src/lattice.rs:70:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by sorami** [comment]
```sh
$ echo "あ" | sudachi
あ      感動詞,フィラー,*,*,*,* あー
EOS

$ echo "阿" | sudachi
thread 'main' panicked at 'EOS isn't connected to BOS', src/lattice.rs:70:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by mh-northlander** [comment]
We can use MecabOOV or SimpleOOV plugin to handle oovs
Note that tokenizer won't run without oov-provider plugins
