### ISSUE TITLE
SudachiError: Invalid i16 literal when building user dictionary

### ISSUE THREAD

**Issue by elda27** [WorksApplications/sudachi.rs#238]
I try to build user dictionary using ubuild on sudachipy (>= 0.6.8).
It hasn't provided any information in the error message for solving the problem.
I replace my work directory with "[root_dir]".

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "[root_dir]\.venv\Scripts\sudachipy.exe\__main__.py", line 7, in <module>
  File "[root_dir]\.venv\Lib\site-packages\sudachipy\command_line.py", line 270, in main
    args.handler(args, args.print_usage)
  File "[root_dir]\.venv\Lib\site-packages\sudachipy\command_line.py", line 192, in _command_user_build
    stats = sudachipy.build_user_dic(
            ^^^^^^^^^^^^^^^^^^^^^^^^^
sudachipy.errors.SudachiError: WindowsPath('[root_dir]/data/dictionary.csv'): [root_dir]\data\dictionary.csv:1      Invalid i16 literal 
```

**Comment by mh-northlander** [comment]
It seems that there are missing entries in the line 1 of your dictionary data CSV (column 1-3 are parsed as i16).
Please refer to [this doument](https://github.com/WorksApplications/Sudachi/blob/develop/docs/user_dict.md) for the specification on creating a user dictionary (only available in Japanese).
