### ISSUE TITLE
The sudachipy executable fails: Package `sudachidict_core` does not exist

### ISSUE THREAD

**Issue by yurivict** [WorksApplications/sudachi.rs#270]
```
$ sudachipy
Traceback (most recent call last):
  File "/usr/local/bin/sudachipy", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sudachipy/command_line.py", line 270, in main
    args.handler(args, args.print_usage)
  File "/usr/local/lib/python3.11/site-packages/sudachipy/command_line.py", line 117, in _command_tokenize
    dict_ = Dictionary(config_path=args.fpath_setting,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sudachipy/__init__.py", line 36, in _find_dict_path
    raise ModuleNotFoundError(
ModuleNotFoundError: Package `sudachidict_core` does not exist. You may install it with a command `$ pip install sudachidict_core`
[yuri@yv /usr/ports/japanese/py-SudachiPy]$ sudachipy
Traceback (most recent call last):
  File "/usr/local/bin/sudachipy", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sudachipy/command_line.py", line 270, in main
    args.handler(args, args.print_usage)
  File "/usr/local/lib/python3.11/site-packages/sudachipy/command_line.py", line 117, in _command_tokenize
    dict_ = Dictionary(config_path=args.fpath_setting,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sudachipy/__init__.py", line 36, in _find_dict_path
    raise ModuleNotFoundError(
ModuleNotFoundError: Package `sudachidict_core` does not exist. You may install it with a command `$ pip install sudachidict_core`
```

List of installed files:
```
$ pkg info -l py311-SudachiPy-0.6.8
py311-SudachiPy-0.6.8:
        /usr/local/bin/sudachipy
        /usr/local/bin/sudachipy-3.11
        /usr/local/lib/python3.11/site-packages/SudachiPy-0.6.8.dist-info/METADATA
        /usr/local/lib/python3.11/site-packages/SudachiPy-0.6.8.dist-info/RECORD
        /usr/local/lib/python3.11/site-packages/SudachiPy-0.6.8.dist-info/WHEEL
        /usr/local/lib/python3.11/site-packages/SudachiPy-0.6.8.dist-info/entry_points.txt
        /usr/local/lib/python3.11/site-packages/SudachiPy-0.6.8.dist-info/top_level.txt
        /usr/local/lib/python3.11/site-packages/sudachipy/__init__.py
        /usr/local/lib/python3.11/site-packages/sudachipy/__pycache__/__init__.cpython-311.opt-1.pyc
        /usr/local/lib/python3.11/site-packages/sudachipy/__pycache__/__init__.cpython-311.pyc
        /usr/local/lib/python3.11/site-packages/sudachipy/__pycache__/command_line.cpython-311.opt-1.pyc
        /usr/local/lib/python3.11/site-packages/sudachipy/__pycache__/command_line.cpython-311.pyc
        /usr/local/lib/python3.11/site-packages/sudachipy/__pycache__/config.cpython-311.opt-1.pyc
        /usr/local/lib/python3.11/site-packages/sudachipy/__pycache__/config.cpython-311.pyc
        /usr/local/lib/python3.11/site-packages/sudachipy/__pycache__/errors.cpython-311.opt-1.pyc
        /usr/local/lib/python3.11/site-packages/sudachipy/__pycache__/errors.cpython-311.pyc
        /usr/local/lib/python3.11/site-packages/sudachipy/command_line.py
        /usr/local/lib/python3.11/site-packages/sudachipy/config.py
        /usr/local/lib/python3.11/site-packages/sudachipy/dictionary/__init__.py
        /usr/local/lib/python3.11/site-packages/sudachipy/dictionary/__pycache__/__init__.cpython-311.opt-1.pyc
        /usr/local/lib/python3.11/site-packages/sudachipy/dictionary/__pycache__/__init__.cpython-311.pyc
        /usr/local/lib/python3.11/site-packages/sudachipy/errors.py
        /usr/local/lib/python3.11/site-packages/sudachipy/morpheme/__init__.py
        /usr/local/lib/python3.11/site-packages/sudachipy/morpheme/__pycache__/__init__.cpython-311.opt-1.pyc
        /usr/local/lib/python3.11/site-packages/sudachipy/morpheme/__pycache__/__init__.cpython-311.pyc
        /usr/local/lib/python3.11/site-packages/sudachipy/morphemelist/__init__.py
        /usr/local/lib/python3.11/site-packages/sudachipy/morphemelist/__pycache__/__init__.cpython-311.opt-1.pyc
        /usr/local/lib/python3.11/site-packages/sudachipy/morphemelist/__pycache__/__init__.cpython-311.pyc
        /usr/local/lib/python3.11/site-packages/sudachipy/resources/char.def
        /usr/local/lib/python3.11/site-packages/sudachipy/resources/rewrite.def
        /usr/local/lib/python3.11/site-packages/sudachipy/resources/sudachi.json
        /usr/local/lib/python3.11/site-packages/sudachipy/resources/unk.def
        /usr/local/lib/python3.11/site-packages/sudachipy/sudachipy.cpython-311.so
        /usr/local/lib/python3.11/site-packages/sudachipy/sudachipy.pyi
        /usr/local/lib/python3.11/site-packages/sudachipy/tokenizer/__init__.py
        /usr/local/lib/python3.11/site-packages/sudachipy/tokenizer/__pycache__/__init__.cpython-311.opt-1.pyc
        /usr/local/lib/python3.11/site-packages/sudachipy/tokenizer/__pycache__/__init__.cpython-311.pyc
        /usr/local/share/licenses/py311-SudachiPy-0.6.8/APACHE20
        /usr/local/share/licenses/py311-SudachiPy-0.6.8/LICENSE
        /usr/local/share/licenses/py311-SudachiPy-0.6.8/catalog.mk
```

The package is built using PEP517 compatible build and install Python modules.

Python-3.11
FreeBSD 14.1

**Comment by mh-northlander** [comment]
In Python version, the default dictionary data is loaded via [SudachiDict_core](https://pypi.org/project/SudachiDict-core/) package, i.e. you also need to install it by `pip install sudachidict_core`.
